"""initial postgres schema

Revision ID: 20260610_0001
Revises: 
Create Date: 2026-06-10 11:21:37.830604
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260610_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_allowlist', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('budget_limit_usd', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'revoked')", name='ck_api_keys_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_tenant_created', 'api_keys', ['tenant_id', 'created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('sequence_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=200), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sequence_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_audit_events_tenant_sequence', 'audit_events', ['tenant_id', 'sequence_id'], unique=False)
    op.create_table('budget_reconciliation_outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.String(length=100), nullable=False),
    sa.Column('api_key_id', sa.String(length=100), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id')
    )
    op.create_index('ix_budget_reconciliation_pending', 'budget_reconciliation_outbox', ['processed_at', 'claim_expires_at', 'id'], unique=False)
    op.create_table('budget_spend',
    sa.Column('api_key_id', sa.String(length=100), nullable=False),
    sa.Column('actual_spend_usd', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('api_key_id')
    )
    op.create_table('configuration_versions',
    sa.Column('version', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'published', 'failed')", name='ck_configuration_versions_status'),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('logical_models',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'disabled', 'deleted')", name='ck_logical_models_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('credential_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('credential_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('credential_key_version', sa.Integer(), nullable=False),
    sa.Column('credential_fingerprint', sa.String(length=16), nullable=False),
    sa.Column('timeout_seconds', sa.Numeric(precision=8, scale=3), server_default='30', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('weight', sa.Integer(), server_default='1', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("protocol IN ('openai-compatible', 'anthropic', 'gemini', 'ollama')", name='ck_provider_connections_protocol'),
    sa.CheckConstraint("status IN ('active', 'disabled', 'deleted')", name='ck_provider_connections_status'),
    sa.CheckConstraint('timeout_seconds > 0', name='ck_provider_connections_timeout'),
    sa.CheckConstraint('weight > 0', name='ck_provider_connections_weight'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('route_decisions',
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('logical_model', sa.String(length=200), nullable=False),
    sa.Column('configuration_version', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('selected_provider_connection_id', sa.String(length=64), nullable=True),
    sa.Column('selected_provider_protocol', sa.String(length=32), nullable=True),
    sa.Column('selected_provider_model', sa.String(length=300), nullable=True),
    sa.Column('attempts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('rejected_candidates', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'request_id')
    )
    op.create_table('sqlite_migration_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_sqlite_migration_runs_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_fingerprint')
    )
    op.create_table('tenant_policies',
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('model_allowlist', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('routing_objective', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('api_key_id', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('logical_model', sa.String(length=200), nullable=False),
    sa.Column('provider_connection_id', sa.String(length=64), nullable=False),
    sa.Column('provider_protocol', sa.String(length=32), nullable=False),
    sa.Column('provider_model', sa.String(length=300), nullable=False),
    sa.Column('configuration_version', sa.BigInteger(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_events_tenant_created_id', 'usage_events', ['tenant_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_usage_events_tenant_id', 'usage_events', ['tenant_id', 'id'], unique=False)
    op.create_table('usage_write_intents',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('api_key_id', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('logical_model', sa.String(length=200), nullable=False),
    sa.Column('configuration_version', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reservation_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name='ck_usage_write_intents_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_usage_write_intents_pending', 'usage_write_intents', ['status', 'created_at'], unique=False)
    op.create_table('configuration_outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('configuration_version', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuration_version'], ['configuration_versions.version'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_configuration_outbox_pending', 'configuration_outbox', ['processed_at', 'claim_expires_at', 'id'], unique=False)
    op.create_table('logical_model_aliases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('logical_model_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logical_model_id'], ['logical_models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', name='uq_logical_model_aliases_alias')
    )
    op.create_table('model_candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('logical_model_id', sa.String(length=200), nullable=False),
    sa.Column('provider_connection_id', sa.String(length=64), nullable=False),
    sa.Column('upstream_model_id', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('weight', sa.Integer(), server_default='1', nullable=False),
    sa.Column('context_window_tokens', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('input_modalities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('output_modalities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tool_modes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('schema_support', sa.String(length=32), server_default='none', nullable=False),
    sa.Column('streaming_support', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('embeddings_support', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('retention_class', sa.String(length=64), server_default='standard', nullable=False),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('native_features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('unsupported_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("schema_support IN ('none', 'json_mode', 'best_effort_schema', 'strict_json_schema')", name='ck_model_candidates_schema_support'),
    sa.CheckConstraint("status IN ('active', 'disabled', 'deleted')", name='ck_model_candidates_status'),
    sa.CheckConstraint('context_window_tokens > 0', name='ck_model_candidates_context'),
    sa.CheckConstraint('max_output_tokens >= 0', name='ck_model_candidates_output'),
    sa.CheckConstraint('weight > 0', name='ck_model_candidates_weight'),
    sa.ForeignKeyConstraint(['logical_model_id'], ['logical_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_connection_id'], ['provider_connections.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_model_id', 'provider_connection_id', 'upstream_model_id', name='uq_model_candidates_mapping')
    )
    op.create_table('sqlite_migration_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('migration_run_id', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('source_cursor', sa.String(length=200), nullable=True),
    sa.Column('rows_imported', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['migration_run_id'], ['sqlite_migration_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('migration_run_id', 'entity', 'source_cursor', name='uq_migration_batch')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_migration_batches')
    op.drop_table('model_candidates')
    op.drop_table('logical_model_aliases')
    op.drop_index('ix_configuration_outbox_pending', table_name='configuration_outbox')
    op.drop_table('configuration_outbox')
    op.drop_index('ix_usage_write_intents_pending', table_name='usage_write_intents')
    op.drop_table('usage_write_intents')
    op.drop_index('ix_usage_events_tenant_id', table_name='usage_events')
    op.drop_index('ix_usage_events_tenant_created_id', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('tenant_policies')
    op.drop_table('sqlite_migration_runs')
    op.drop_table('route_decisions')
    op.drop_table('provider_connections')
    op.drop_table('logical_models')
    op.drop_table('configuration_versions')
    op.drop_table('budget_spend')
    op.drop_index('ix_budget_reconciliation_pending', table_name='budget_reconciliation_outbox')
    op.drop_table('budget_reconciliation_outbox')
    op.drop_index('ix_audit_events_tenant_sequence', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_api_keys_tenant_created', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
