from __future__ import annotations

from mixapi.models import LogicalModel, ProviderModel


def default_catalog() -> dict[str, LogicalModel]:
    chat_candidates = (
        ProviderModel(
            id="openai:gpt-4.1-mini",
            provider="openai",
            provider_model_id="gpt-4.1-mini",
            logical_model_id="mixapi/balanced-chat",
            status="active",
            context_window_tokens=128_000,
            max_output_tokens=16_384,
            input_modalities=("text", "image"),
            output_modalities=("text",),
            tool_modes=("function",),
            schema_support="strict_json_schema",
            streaming_support=True,
            embeddings_support=False,
            retention_class="standard",
            regions=("us", "eu"),
            pricing={"input_per_million": "0.40", "output_per_million": "1.60"},
            native_features=("responses",),
        ),
        ProviderModel(
            id="anthropic:claude-sonnet-4",
            provider="anthropic",
            provider_model_id="claude-sonnet-4",
            logical_model_id="mixapi/balanced-chat",
            status="active",
            context_window_tokens=200_000,
            max_output_tokens=16_384,
            input_modalities=("text", "image"),
            output_modalities=("text",),
            tool_modes=("function",),
            schema_support="best_effort_schema",
            streaming_support=True,
            embeddings_support=False,
            retention_class="standard",
            regions=("us",),
            pricing={"input_per_million": "3.00", "output_per_million": "15.00"},
            native_features=("messages",),
        ),
        ProviderModel(
            id="gemini:gemini-2.5-flash",
            provider="gemini",
            provider_model_id="gemini-2.5-flash",
            logical_model_id="mixapi/balanced-chat",
            status="active",
            context_window_tokens=1_000_000,
            max_output_tokens=65_536,
            input_modalities=("text",),
            output_modalities=("text",),
            tool_modes=("function",),
            schema_support="strict_json_schema",
            streaming_support=True,
            embeddings_support=False,
            retention_class="standard",
            regions=("us", "eu"),
            pricing={"input_per_million": "0.30", "output_per_million": "2.50"},
            native_features=("generate_content",),
        ),
        ProviderModel(
            id="ollama:llama3.1",
            provider="ollama",
            provider_model_id="llama3.1",
            logical_model_id="mixapi/balanced-chat",
            status="active",
            context_window_tokens=32_000,
            max_output_tokens=8_192,
            input_modalities=("text",),
            output_modalities=("text",),
            tool_modes=(),
            schema_support="json_mode",
            streaming_support=True,
            embeddings_support=False,
            retention_class="local",
            regions=("local",),
            pricing={"input_per_million": "0.00", "output_per_million": "0.00"},
            native_features=("local",),
        ),
    )
    embedding_candidates = (
        ProviderModel(
            id="openai:text-embedding-3-small",
            provider="openai",
            provider_model_id="text-embedding-3-small",
            logical_model_id="mixapi/embedding-small",
            status="active",
            context_window_tokens=8_191,
            max_output_tokens=0,
            input_modalities=("text",),
            output_modalities=("embedding",),
            tool_modes=(),
            schema_support="none",
            streaming_support=False,
            embeddings_support=True,
            retention_class="standard",
            regions=("us", "eu"),
            pricing={"input_per_million": "0.02"},
            native_features=("embeddings",),
        ),
        ProviderModel(
            id="ollama:nomic-embed-text",
            provider="ollama",
            provider_model_id="nomic-embed-text",
            logical_model_id="mixapi/embedding-small",
            status="active",
            context_window_tokens=8_192,
            max_output_tokens=0,
            input_modalities=("text",),
            output_modalities=("embedding",),
            tool_modes=(),
            schema_support="none",
            streaming_support=False,
            embeddings_support=True,
            retention_class="local",
            regions=("local",),
            pricing={"input_per_million": "0.00"},
            native_features=("local", "embeddings"),
        ),
    )
    return {
        "mixapi/balanced-chat": LogicalModel(
            id="mixapi/balanced-chat",
            status="active",
            description="Balanced multi-provider text model",
            candidates=chat_candidates,
        ),
        "mixapi/embedding-small": LogicalModel(
            id="mixapi/embedding-small",
            status="active",
            description="Small embedding model",
            candidates=embedding_candidates,
        ),
    }
